import unreal
import os
import sys
import csv

# 현재는 따로 폴더 생성 기능 제공 안함.

# 프로젝트 명
project_name = "RottenPotato"

# CSV 파일이 존재하는 폴더 경로
csv_folder = unreal.SystemLibrary.get_project_directory() + "CSV"

# c++ struct 를 저장할 폴더 경로 ->
struct_save_folder = unreal.SystemLibrary.get_project_directory() + "Source/" + project_name + "/Public/Table"


# 개행 함수
def next_line(file):
    file.write("\n")


# 타입 선별 함수
def get_unreal_type(type):

    str_type = str(type).lower()

    if str_type == "int" or str_type == "int32":
        return "int32"
    elif str_type == "float" or str_type == "float32":
        return "float"
    elif str_type == "string" or str_type == "fstring":
        return "FString"
    elif str_type == "bool" or str_type == "boolean":
        return "bool"
    elif str_type == "vector" or str_type == "vector3":
        return "FVector"
    elif str_type == "rotator" or str_type == "rotator":
        return "FRotator"
    elif str_type == "text":
        return "FText"
    elif str_type == "color" or str_type == "coloru8":
        return "FLinearColor"
    else:
        unreal.log_error(str_type + " << This type is not allowed. It will change to \'FString\'.")
        return "FString"


# 스크립트 작성 함수
def create_struct():
    print("#######   Data Table C++ Struct Generator Started!     #######")
    print("######    Target CSV Folder : " + csv_folder)
    print("-")
    # csv_folder 내부의 모든 파일 리스트 검출
    file_list = os.listdir(csv_folder)

    csv_file_list = []
    # CSV 가 아닌 것 걸러내기
    for file in file_list:
        if file.endswith(".csv"):
            csv_file_list.append(file)

    if len(csv_file_list) == 0:
        unreal.log_error("There's no CSV file in folder : " + path.csv_folder)
        sys.exit(0)

    print("----------- CSV File List ------------")
    print("-")
    # 반복문 시작 : 하나 씩 변환 시작
    index = 1
    for file in csv_file_list:
        print("(" + str(index) + ") " + file)
        index += 1

    print("-")
    for file in csv_file_list:
        print("-")
        print("::::::::::::: Start making [" + file + "] ::::::::::::::")
        # csv 파일 경로 추출
        csv_file_path = os.path.join(csv_folder, file)

        # 먼저 C++ 부터 작성
        print("----------    Writing C++ Struct row table...   -------------")
        print("-")
        # CSV 를 행 별로 저장
        rows = []
        # 파일 열고 행 별로 rows 에 담는다
        with open(csv_file_path, 'r') as csvfile:
            csv_reader = csv.reader(csvfile)
            for row in csv_reader:
                rows.append(row)

        # 행이 아무것도 없다면 종료
        if len(rows) == 0:
            unreal.log_error("CSV row count is 0")
            continue

        # Id 로 시작하는 행을 찾기 위해 초기값 -1 로 설정
        column_name_row_index = -1
        for data in rows:
            if data[0] == "Id" or str(data[0]).lower() == "id":
                column_name_row_index = rows.index(data)

        if column_name_row_index == -1:
            unreal.log_error("Cannot found Id column")
            continue

        type_name_list = []
        column_name_list = []
        # 타입 이름과 컬럼 이름 수집
        column_name_row = rows[column_name_row_index]
        for index, column_name in enumerate(column_name_row):
            # '#' 으로 시작하는 칼럼은 추가하지 않는다.
            if not column_name.startswith("#"):
                # Id 칼럼 위 행은 타입 행이므로 -1 한 위치에서 타입 이름을 저장.
                # rows[Id 칼럼의 윗 행 인덱스][현재 열 인덱스]
                type_row = rows[column_name_row_index - 1]
                type_name_list.append(type_row[index])
                column_name_list.append(column_name)

        # 타입 갯수와 칼럼 열 갯수가 다르면 경고 후 스킵
        if len(type_name_list) != len(column_name_list):
            print("Type name count and column name count is not correct : " + len(type_name_list) + "/" + len(
                column_name_list))
            continue
        # 파일명 추출
        file_name = os.path.basename(csv_file_path)
        file_name = str(file_name).split('.')[0]
        # 파일 작성 시작
        with open(struct_save_folder + "/F" + file_name + ".h", 'w') as c_file:
            c_file.writelines("// Copyright Parrot_Yong, MIT LICENSE\n")
            c_file.writelines("// This file is auto generated by Parrot_Yong's table generator.\n")
            next_line(c_file)
            c_file.writelines("# pragma once\n")
            next_line(c_file)
            c_file.writelines("#include \"Engine/DataTable.h\"\n")
            c_file.writelines("#include \"F" + file_name + ".generated.h\"\n")
            next_line(c_file)
            c_file.writelines("USTRUCT(Blueprintable)\n")
            c_file.writelines("struct F" + file_name + " : public FTableRowBase\n")
            c_file.writelines("{\n")
            c_file.writelines("\tGENERATED_USTRUCT_BODY()\n")
            next_line(c_file)
            c_file.writelines("public:\n")
            next_line(c_file)
            # 변수 선언
            for index, value in enumerate(column_name_list):
                # id 변수는 선언하지 않는다 -> 기본적으로 Row Name 칼럼이 Id 역할을 해주기 때문.
                if str(value).lower() == "id":
                    continue
                c_file.writelines("\tUPROPERTY(EditAnywhere, BlueprintReadWrite)\n")
                c_file.writelines("\t" + get_unreal_type(type_name_list[index]) + " " + str(value) + ";\n")
                next_line(c_file)

            c_file.writelines("};\n")

        # struct_path : ex) "/Script/project_name.TestTable"
        # unreal_struct_path = "/Script/" + project_name + "." + file_name


# 실행 부분
create_struct()
print("********* C++ Struct Generator Closed. **********")
